export enum NotificationStatusCode {
  BOOKING_CREATED = 1,
  BOOKING_STARTED = 2,
  BOOKING_CUSTOMER_CANCELLED = 3,
  BOOKING_RESTAURANT_CANCELLED = 4,
  BOOKING_COMPLETED = 5,
  BOOKING_ADD_REVIEW = 6,
  BOOKING_START_REMINDER = 7,
  BOOKING_CUSTOMER_CHECKIN = 8,
  BOOKING_UPDATED = 9,
  CHAT_MESSAGE = 10,

  // Interest Flow
  INTEREST_INVITE = 11,
  INTEREST_ACCEPTED = 12,
  INTEREST_DECLINED = 13,
  INTEREST_SUGGESTED_NEW_TIME = 14,
  INTEREST_SLOT_UPDATED = 15,
  INTEREST_CONFIRMED = 16,
}
