import PostgresDataSource from '../data-source';
import User from '../models/User';
import Restaurant from '../models/Restaurant';
import Roles from '../models/Role';
import PasswordResetOTP from '../models/PasswordResetOTP';
import SignUpOtp from '../models/SignUpOtp';
import Password from '../models/Password';
import SocialLogin from '../models/SocialLogin';
import CuisineType from '../models/CuisineType';
import DeletedUsers from '../models/DeletedUsers';
import DeleteReason from '../models/DeleteReason';
import OperationalHour from '../models/OperationalHours';
import Slot from '../models/Slots';
import Booking from '../models/booking';
import Review from '../models/Review';
import Notification from '../models/Notifications';
import RestaurantImages from '../models/RestaurantImages';
import HelpAndSupport from '../models/HelpAndSupport';
import PaymentMethods from '../models/PaymentMethods';
import RestaurantPaymentMethods from '../models/RestaurantPaymentMethods';
import FavouriteRestaurant from '../models/FavouriteRestaurant';
import UnavailableSlot from '../models/UnavailableSlot';
import BusinessProfile from '../models/BusinessProfile';
import OpeningHours from '../models/OpeningHours';
import Producer from '../models/Producer';
import Event from '../models/Event';
import Photo from '../models/Photos';

export const UserRepository = PostgresDataSource.getRepository(User);
export const RolesRepository = PostgresDataSource.getRepository(Roles);
export const PasswordResetOTPRepository = PostgresDataSource.getRepository(PasswordResetOTP);
export const SignUpOTPRepository = PostgresDataSource.getRepository(SignUpOtp);
export const PasswordRepository = PostgresDataSource.getRepository(Password);
export const RestaurantRepository = PostgresDataSource.getRepository(Restaurant);
export const SocialLoginRepository = PostgresDataSource.getRepository(SocialLogin);
export const CuisineTypeRepository = PostgresDataSource.getRepository(CuisineType);
export const DeletedUsersRepository = PostgresDataSource.getRepository(DeletedUsers);
export const DeleteReasonRepository = PostgresDataSource.getRepository(DeleteReason);
export const OperationalHourRepository = PostgresDataSource.getRepository(OperationalHour);
export const SlotRepository = PostgresDataSource.getRepository(Slot);
export const BookingRepository = PostgresDataSource.getRepository(Booking);
export const ReviewRepository = PostgresDataSource.getRepository(Review);
export const NotificationRepository = PostgresDataSource.getRepository(Notification);
export const RestaurantImagesRepository = PostgresDataSource.getRepository(RestaurantImages);
export const HelpAndSupportRepository = PostgresDataSource.getRepository(HelpAndSupport);
export const PaymentMethodsRepository = PostgresDataSource.getRepository(PaymentMethods);
export const RestaurantPaymentMethodsRepository = PostgresDataSource.getRepository(RestaurantPaymentMethods);
export const FavouriteRestaurantRepository = PostgresDataSource.getRepository(FavouriteRestaurant);
export const UnavailableSlotRepository = PostgresDataSource.getRepository(UnavailableSlot);
export const BusinessProfileRepository = PostgresDataSource.getRepository(BusinessProfile);
export const OpeningHoursRepository = PostgresDataSource.getRepository(OpeningHours);
export const ProducerRepository = PostgresDataSource.getRepository(Producer);
export const EventRepository = PostgresDataSource.getRepository(Event);
export const PhotoRepository = PostgresDataSource.getRepository(Photo);