export const mapBusinessProfile = (profile: any) => ({
  businessName: profile.businessName,
  address: profile.address,
  phoneNumber: profile.phoneNumber,
  website: profile.website,
  instagram: profile.instagram,
  twitter: profile.twitter,
  facebook: profile.facebook,
  description: profile.description,
  profileImageUrl: profile.profileImageUrl,
});

export const mapProducer = (producer: any) => ({
  id: producer.id,
  name: producer.name,
  address: producer.address,
  city: producer.city,
  country: producer.country,
  placeId: producer.placeId,
  type: producer.type,
  serviceType: producer.serviceType,
  status: producer.status,
  totalCapacity: producer.totalCapacity,
  document1: producer.document1,
  document2: producer.document2,
  mapsUrl: producer.mapsUrl,
  latitude: producer.latitude,
  longitude: producer.longitude,
  website: producer.website,
  phoneNumber: producer.phoneNumber,
  rating: producer.rating,
  createdAt: producer.createdAt,
  updatedAt: producer.updatedAt,
});
